version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      CHAIN_ID: testNet
      NODE_ENV: development
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:13.0
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db