version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
      - edgeware_develop
    links:
      - postgres
      - edgeware_develop
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      CHAIN_ID: testNet
      NODE_ENV: development
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:13.0
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      
  edgeware_develop:
    image: eteissonniere/edgeware:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_edg:/data/chains
    ports:
      - "127.0.0.1:9933:9933"
      - "0.0.0.0:9944:9944"
      - "127.0.0.1:30333:30333"
    command: ['--dev', '--ws-external', '--rpc-cors','all' ]